language: r
cache: packages
sudo: required
apt_packages:
  - libfftw3-dev
r_packages:
  - devtools
  - covr
  - recipes
  - fftw
r_github_packages:
  - jkennel/earthtide
after_success:
  - Rscript -e 'covr::codecov()'