// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// distributed_lag_parallel
arma::mat distributed_lag_parallel(const arma::vec& x, const arma::mat& bl, int lag_max);
RcppExport SEXP _waterlevel_distributed_lag_parallel(SEXP xSEXP, SEXP blSEXP, SEXP lag_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bl(blSEXP);
    Rcpp::traits::input_parameter< int >::type lag_max(lag_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(distributed_lag_parallel(x, bl, lag_max));
    return rcpp_result_gen;
END_RCPP
}
// harmonic
Rcpp::NumericMatrix harmonic(arma::vec times, arma::vec& freq);
RcppExport SEXP _waterlevel_harmonic(SEXP timesSEXP, SEXP freqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type times(timesSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type freq(freqSEXP);
    rcpp_result_gen = Rcpp::wrap(harmonic(times, freq));
    return rcpp_result_gen;
END_RCPP
}
// shift_subset
Rcpp::NumericVector shift_subset(Rcpp::NumericVector x, int lag, int n_subset, int n_shift);
RcppExport SEXP _waterlevel_shift_subset(SEXP xSEXP, SEXP lagSEXP, SEXP n_subsetSEXP, SEXP n_shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type n_subset(n_subsetSEXP);
    Rcpp::traits::input_parameter< int >::type n_shift(n_shiftSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_subset(x, lag, n_subset, n_shift));
    return rcpp_result_gen;
END_RCPP
}
// lag_matrix
Rcpp::NumericMatrix lag_matrix(Rcpp::NumericVector x, Rcpp::IntegerVector lags, int n_subset, int n_shift, std::string var_name);
RcppExport SEXP _waterlevel_lag_matrix(SEXP xSEXP, SEXP lagsSEXP, SEXP n_subsetSEXP, SEXP n_shiftSEXP, SEXP var_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< int >::type n_subset(n_subsetSEXP);
    Rcpp::traits::input_parameter< int >::type n_shift(n_shiftSEXP);
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(lag_matrix(x, lags, n_subset, n_shift, var_name));
    return rcpp_result_gen;
END_RCPP
}
// det_vector
arma::cx_vec det_vector(const arma::cx_cube& x);
RcppExport SEXP _waterlevel_det_vector(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cx_cube& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(det_vector(x));
    return rcpp_result_gen;
END_RCPP
}
// solve_tf
arma::cx_mat solve_tf(arma::cx_cube x);
RcppExport SEXP _waterlevel_solve_tf(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cx_cube >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_tf(x));
    return rcpp_result_gen;
END_RCPP
}
// det_parallel
arma::cx_vec det_parallel(arma::cx_cube& a);
RcppExport SEXP _waterlevel_det_parallel(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cx_cube& >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(det_parallel(a));
    return rcpp_result_gen;
END_RCPP
}
// solve_tf_parallel
arma::cx_mat solve_tf_parallel(arma::cx_cube a);
RcppExport SEXP _waterlevel_solve_tf_parallel(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cx_cube >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_tf_parallel(a));
    return rcpp_result_gen;
END_RCPP
}
// calc_b_vals
arma::vec calc_b_vals(int b, const arma::vec& wb);
RcppExport SEXP _waterlevel_calc_b_vals(SEXP bSEXP, SEXP wbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wb(wbSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_b_vals(b, wb));
    return rcpp_result_gen;
END_RCPP
}
// konno_ohmachi
double konno_ohmachi(const arma::vec& b_vals, const arma::vec& ref_z, const arma::vec& f, const arma::vec& x, int i);
RcppExport SEXP _waterlevel_konno_ohmachi(SEXP b_valsSEXP, SEXP ref_zSEXP, SEXP fSEXP, SEXP xSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b_vals(b_valsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ref_z(ref_zSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type f(fSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(konno_ohmachi(b_vals, ref_z, f, x, i));
    return rcpp_result_gen;
END_RCPP
}
// konno_ohmachi_parallel
arma::vec konno_ohmachi_parallel(const arma::vec& x, const arma::vec& f, int b);
RcppExport SEXP _waterlevel_konno_ohmachi_parallel(SEXP xSEXP, SEXP fSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type f(fSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(konno_ohmachi_parallel(x, f, b));
    return rcpp_result_gen;
END_RCPP
}
// konno_ohmachi_serial
arma::vec konno_ohmachi_serial(const arma::vec& x, const arma::vec& f, int b);
RcppExport SEXP _waterlevel_konno_ohmachi_serial(SEXP xSEXP, SEXP fSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type f(fSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(konno_ohmachi_serial(x, f, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_waterlevel_distributed_lag_parallel", (DL_FUNC) &_waterlevel_distributed_lag_parallel, 3},
    {"_waterlevel_harmonic", (DL_FUNC) &_waterlevel_harmonic, 2},
    {"_waterlevel_shift_subset", (DL_FUNC) &_waterlevel_shift_subset, 4},
    {"_waterlevel_lag_matrix", (DL_FUNC) &_waterlevel_lag_matrix, 5},
    {"_waterlevel_det_vector", (DL_FUNC) &_waterlevel_det_vector, 1},
    {"_waterlevel_solve_tf", (DL_FUNC) &_waterlevel_solve_tf, 1},
    {"_waterlevel_det_parallel", (DL_FUNC) &_waterlevel_det_parallel, 1},
    {"_waterlevel_solve_tf_parallel", (DL_FUNC) &_waterlevel_solve_tf_parallel, 1},
    {"_waterlevel_calc_b_vals", (DL_FUNC) &_waterlevel_calc_b_vals, 2},
    {"_waterlevel_konno_ohmachi", (DL_FUNC) &_waterlevel_konno_ohmachi, 5},
    {"_waterlevel_konno_ohmachi_parallel", (DL_FUNC) &_waterlevel_konno_ohmachi_parallel, 3},
    {"_waterlevel_konno_ohmachi_serial", (DL_FUNC) &_waterlevel_konno_ohmachi_serial, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_waterlevel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
